apiVersion: apps/v1
kind: Deployment
metadata:
  name: oidc-discovery-provider
  namespace: spire-system
  labels:
    app: oidc-discovery-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oidc-discovery-provider
  template:
    metadata:
      labels:
        app: oidc-discovery-provider
    spec:
      serviceAccountName: spire-server
      containers:
      - name: oidc-discovery-provider
        image: ghcr.io/spiffe/oidc-discovery-provider:1.9.6
        imagePullPolicy: IfNotPresent
        args:
          - "-config"
          - "/run/oidc-discovery-provider/config/oidc-discovery-provider.conf"
        ports:
        - name: oidc-http
          containerPort: 8008
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /run/oidc-discovery-provider/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: oidc-discovery-provider
