apiVersion: apps/v1
kind: Deployment
metadata:
  name: openbao
  namespace: openbao
  labels:
    app: openbao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openbao
  template:
    metadata:
      labels:
        app: openbao
    spec:
      containers:
        - name: openbao
          image: quay.io/openbao/openbao:2.0.1
          args:
            - server
            - -dev
            - -dev-root-token-id=root
            - -dev-listen-address=0.0.0.0:8200
          ports:
            - containerPort: 8200
              name: http
              protocol: TCP
          env:
            - name: BAO_DEV_ROOT_TOKEN_ID
              value: "root"
            - name: BAO_ADDR
              value: "http://0.0.0.0:8200"
            - name: BAO_LOG_LEVEL
              value: "debug"
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
